---
---
---

## References

### Primary Sources

Anon., 'About', *Dutch Club Brisbane NAQ,* n.d., from <https://www.dutchclubbrisbanenaq.com/go/about/,>
accessed 14 June 2022.

Anon., 'Archerfield', *Queensland Places,* n.d., from <https://queenslandplaces.com.au/archerfield,>
accessed 11 June 2022.

Anon., 'Brisbane's Fine Airport', photograph, 1934, from [https://queenslandplaces.com.au/exhibit/book/ps388,](https://queenslandplaces.com.au/exhibit/book/ps388,) accessed June 1 2022.

Anon., 'Control tower at Archerfield Airport, 1964', photograph, 1964, from <http://hdl.handle.net/10462/deriv/118432,> accessed 1 June 2022.

Anon., (Queensland Main Roads Commission), *The History of the Queensland Main Roads Commission during World War II 1939-1945,* Brisbane, Main Roads Commission, 1949.

Archerfield Airport Corporation, 'God's Acre Cemetery Remembrance Day 2016', media release, Archerfield Airport Corporation, 13 June 2016.

Archerfield Airport Corporation, 'Untitled publicity photograph', photograph, n.d.

*Courier Mail,* Brisbane.

*Daily Mercury,* Mackay.

*Examiner,* Launceston.

Hall, Bruce 'Photograph of Archerfield Airport', photograph, n.d., from <https://www.ozatwar.com/ozatwar/wmyers.htm,> accessed 1 June 2022.

Hall, Bruce 'Photograph of Archerfield Airport -- military assets', photograph, n.d., from <https://www.ozatwar.com/ozatwar/wmyers.htm,> accessed 1 June 2022.

McLennan, Deane Andrew 'God's Acre Cemetery (2020), photograph, 28 December 2020, in author's possession.

Photograph of the Kingsford Smith's "Lady Southern Cross" at Archerfield Airport, Brisbane, QLD, 1934, from <https://collection.maas.museum/object/416306>, accessed 1 June 2022.

Qimagery, 'Aerial Survey of Archerfield', photograph, 20 April 1936, from <http://qimagery.qld.gov.au/,> accessed May 31 2022.

*Telegraph,* Brisbane.

*Warwick Daily News,* Warwick.

### Secondary Sources

Alexander, Kristen 'Lores Bonney: A woman of achievement', *Queensland History Journal,* vol. 23, no. 4, 2017, pp. 221-238.

Anon., 'Brisbane City Council', 'Archerfield Airport -- Administration Building, Aerodrome terminal building, hangars, and interwar buildings', *Local Heritage Places,* September 2020, from [https://heritage.brisbane.qld.gov.au/heritage-places/144,](https://heritage.brisbane.qld.gov.au/heritage-places/144,) accessed June 2022.

Archer, D. 'Data mining and word frequency analysis', in *Research methods for reading digital data in the digital humanities,* G. Griffin & M. Hayler, (eds.), Edinburgh, Edinburgh University Press, 2016.

Dennis, Valerie R. 'Wings and windsocks: Archerfield aerodrome within the Australian airport system 1920-1988', unpublished Ph.D. thesis, University of Queensland, 2004.

Drucker, Joanna *Data Modeling and use,* Routledge, eBook, 2021.

Jones, Steven E. *The Emergence of the Digital Humanities,* New York, Routledge, 2014.

Marks, Roger R. *Queensland Airfields WW2 -- 50 Years On,* Mansfield, Australia, Merino Lithographics, 1994.

Meyer, E.T. and Schroeder, R *Knowledge Machines: Digital transformations of the sciences and humanities,* Cambridge, M.I.T. Press, 2015.

Prangley, Dean N.W. 'The Eagle Farm agricultural establishment', *Queensland History Journal,* vol. 21, no. 12, 2013, pp. 839-846.

Price, Jeffrey, and Forrest, Jeffrey S. *Practical Aviation Security: Predicting and Preventing Future Threats,* 2^nd^ edn, Oxford, Oxford University Press, 2013.

Swain, Shurlee, Musgrove, Nell, O'Neill, Cate, and Thurley-Hart, Constance 'Trove and the history of childhood -- combining microhistory and big data', *History Australia,* vol. 18, no. 4, 2021, pp. 840-845.

Tisdell, Lucas, Zhang, Yahua, and Zhang, Anming 'Development challenges facing general aviation airports: a case study of Archerfield Airport, Queensland, Australia', *Case Studies on Transport Policy,* vol.
8, no. 4, 2020, pp. 1458-1467.
